---
version: '2'

networks:
  cida-auth-net:

services:
  ldap-server:
    image: osixia/openldap:1.1.7
    container_name: openldap
    hostname: ldap-cida-auth.org
    ports:
      - "389:389"
    networks:
      cida-auth-net:
        aliases:
          - ldap-server
    volumes:
      - /etc/ldap
      - /var/lib/ldap
    env_file:
      - "compose${AUTH_ENV_LOCAL}.env"

  # This container starts but waits for the LDAP server to come up
  # before running its main command. Check Dockerfile for more info.
  ldap-seed:
    image: usgs/auth-ldap-seed:1.2.7-1
    build:
      context: ./auth-ldap
      args:
        - doi_network=$doi_network
    container_name: auth-ldap-seed
    volumes:
      - ./auth-ldap/ldif_files:/ldif_files/
    links:
      - ldap-server
    networks:
      cida-auth-net:
        aliases:
          - ldap-server
    entrypoint: dockerize -wait tcp://ldap-server:389 sh -c '/ldif_files/addAll.sh'
    depends_on:
      - ldap-server

  auth-database:
    image: usgs/auth-database:1.2.7-1
    build:
      context: ./auth-database
      args:
        - doi_network=$doi_network
    ports:
      - "5432:5432"
    networks:
      cida-auth-net:
        aliases:
          - auth-database
    env_file:
      - "compose${AUTH_ENV_LOCAL}.env"

  auth-manager-console:
    image: usgs/auth-manager-console:1.2.7-1
    build:
      context: ./auth-manager-console
      args:
        - doi_network=$doi_network
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      cida-auth-net:
        aliases:
          - auth-manager-console
    env_file:
      - "compose${AUTH_ENV_LOCAL}.env"
    depends_on:
      - auth-manager-core

  auth-manager-core:
    image: usgs/auth-manager-core:1.2.7-1
    build:
      context: ./auth-manager-core
      args:
        - doi_network=$doi_network
    ports:
      - "8082:8080"
      - "8083:8081"
    networks:
      cida-auth-net:
        aliases:
          - auth-manager-core
    command: dockerize -wait tcp://auth-database:5432 -timeout 60s catalina.sh run
    env_file:
      - "compose${AUTH_ENV_LOCAL}.env"
    depends_on:
      - auth-database
