---
  LDAP_DOMAIN: wma.usgs.gov
  LDAP_BASE_DN: dc=wma,dc=usgs,dc=gov
  LDAP_ORGANISATION: USGS Water Mission Area
  LDAP_REMOVE_CONFIG_AFTER_SETUP: false
  LDAP_TLS: true
  LDAP_TLS_CRT_FILENAME: ldap-server.cer
  LDAP_TLS_KEY_FILENAME: ldap-server.key
  LDAP_TLS_CA_CRT_FILENAME: ldap-root.cer
  LDAP_TLS_ENFORCE: true
  LDAP_TLS_CIPHER_SUITE: SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC
  LDAP_TLS_VERIFY_CLIENT: try
  LDAP_BACKEND: mdb
